version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: uppetit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./uppetit-tv-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@db:5432/uppetit_db?schema=public
    depends_on:
      - db

  frontend:
    build: ./uppetit-tv-admin
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: